### ISSUE TITLE
Please add README.md

### ISSUE THREAD

**Issue by manid2** [spratik/imageGenerater#1]
Hi @spratik ,

May I know a more about this project? Add a **README**, explain its purpose.
Also I noticed myfile1 of `ofstream` class is not closed at the end of the program.
Please close it as I do not have the write access to the repo.

Thank you,
Mani :green_apple:

**Comment by spratik** [comment]
please check Readme.md

**Comment by manid2** [comment]
Thank you, @spratik 😃 

But the README is poorly formatted. Can you please improve it?
Separate the Heading from the body.

Thank you,
Mani🍏

**Comment by manid2** [comment]
.
